"""initial_schema_with_19_entities

Revision ID: da16b99afdae
Revises: 
Create Date: 2026-09-26 22:24:31.816730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da16b99afdae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('currency_symbol', sa.String(length=5), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_table('audit_events',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('old_values_json', sa.Text(), nullable=True),
    sa.Column('new_values_json', sa.Text(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_id'), 'audit_events', ['id'], unique=False)
    op.create_table('business_services',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('business_impact_score', sa.Float(), nullable=True),
    sa.Column('financial_loss_per_hour', sa.Float(), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('current_risk_score', sa.Float(), nullable=True),
    sa.Column('current_likelihood', sa.Float(), nullable=True),
    sa.Column('current_impact', sa.Float(), nullable=True),
    sa.Column('trend', sa.String(length=20), nullable=True),
    sa.Column('top_driver', sa.String(length=255), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_services_id'), 'business_services', ['id'], unique=False)
    op.create_table('evidence_sources',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('freshness_score', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('total_records', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_sources_id'), 'evidence_sources', ['id'], unique=False)
    op.create_table('investment_initiatives',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('one_time_cost', sa.Float(), nullable=False),
    sa.Column('recurring_cost', sa.Float(), nullable=True),
    sa.Column('expected_risk_reduction', sa.Float(), nullable=False),
    sa.Column('affected_services_json', sa.Text(), nullable=True),
    sa.Column('affected_controls_json', sa.Text(), nullable=True),
    sa.Column('implementation_weeks', sa.Integer(), nullable=True),
    sa.Column('capacity_requirement', sa.String(length=50), nullable=True),
    sa.Column('is_mandatory', sa.Boolean(), nullable=True),
    sa.Column('dependencies_json', sa.Text(), nullable=True),
    sa.Column('confidence_pct', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investment_initiatives_code'), 'investment_initiatives', ['code'], unique=True)
    op.create_index(op.f('ix_investment_initiatives_id'), 'investment_initiatives', ['id'], unique=False)
    op.create_table('model_versions',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=True),
    sa.Column('weights_json', sa.Text(), nullable=True),
    sa.Column('assumptions_json', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_versions_id'), 'model_versions', ['id'], unique=False)
    op.create_table('optimization_runs',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=False),
    sa.Column('objective', sa.String(length=100), nullable=True),
    sa.Column('selected_initiatives_json', sa.Text(), nullable=True),
    sa.Column('initial_risk', sa.Float(), nullable=False),
    sa.Column('optimized_risk', sa.Float(), nullable=False),
    sa.Column('risk_reduction', sa.Float(), nullable=False),
    sa.Column('budget_used', sa.Float(), nullable=False),
    sa.Column('budget_remaining', sa.Float(), nullable=False),
    sa.Column('roi_metric', sa.Float(), nullable=True),
    sa.Column('solver_status', sa.String(length=50), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('execution_time_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_optimization_runs_id'), 'optimization_runs', ['id'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('likelihood', sa.Float(), nullable=False),
    sa.Column('impact', sa.Float(), nullable=False),
    sa.Column('exposure_mod', sa.Float(), nullable=True),
    sa.Column('control_mod', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('snapshot_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assumptions_json', sa.Text(), nullable=True),
    sa.Column('drivers_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_snapshots_entity_id'), 'risk_snapshots', ['entity_id'], unique=False)
    op.create_index(op.f('ix_risk_snapshots_id'), 'risk_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_risk_snapshots_snapshot_date'), 'risk_snapshots', ['snapshot_date'], unique=False)
    op.create_table('scenarios',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('baseline_risk', sa.Float(), nullable=False),
    sa.Column('scenario_risk', sa.Float(), nullable=False),
    sa.Column('risk_reduction', sa.Float(), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('changes_json', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenarios_id'), 'scenarios', ['id'], unique=False)
    op.create_table('security_controls',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('coverage_pct', sa.Float(), nullable=True),
    sa.Column('effectiveness_pct', sa.Float(), nullable=True),
    sa.Column('risk_reduction_weight', sa.Float(), nullable=True),
    sa.Column('evidence_quality_score', sa.Float(), nullable=True),
    sa.Column('last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_controls_code'), 'security_controls', ['code'], unique=True)
    op.create_index(op.f('ix_security_controls_id'), 'security_controls', ['id'], unique=False)
    op.create_table('users',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id_code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=100), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('hostname', sa.String(length=255), nullable=True),
    sa.Column('exposure', sa.String(length=50), nullable=True),
    sa.Column('criticality', sa.String(length=50), nullable=True),
    sa.Column('owner', sa.String(length=255), nullable=True),
    sa.Column('data_classification', sa.String(length=50), nullable=True),
    sa.Column('control_coverage', sa.Float(), nullable=True),
    sa.Column('current_risk_score', sa.Float(), nullable=True),
    sa.Column('current_likelihood', sa.Float(), nullable=True),
    sa.Column('current_impact', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['business_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_id_code'), 'assets', ['asset_id_code'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('decision_approvals',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('optimization_run_id', sa.String(length=36), nullable=False),
    sa.Column('investment_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['optimization_run_id'], ['optimization_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_approvals_id'), 'decision_approvals', ['id'], unique=False)
    op.create_table('evidence_records',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('record_type', sa.String(length=50), nullable=True),
    sa.Column('raw_payload_json', sa.Text(), nullable=False),
    sa.Column('normalized_payload_json', sa.Text(), nullable=True),
    sa.Column('data_quality_score', sa.Float(), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.Column('validation_errors_json', sa.Text(), nullable=True),
    sa.Column('ingestion_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['evidence_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_records_id'), 'evidence_records', ['id'], unique=False)
    op.create_table('risk_drivers',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('driver_type', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('impact_contribution', sa.Float(), nullable=False),
    sa.Column('affected_assets_count', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['snapshot_id'], ['risk_snapshots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_drivers_id'), 'risk_drivers', ['id'], unique=False)
    op.create_table('scenario_results',
    sa.Column('scenario_id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=False),
    sa.Column('entity_name', sa.String(length=255), nullable=False),
    sa.Column('baseline_score', sa.Float(), nullable=False),
    sa.Column('projected_score', sa.Float(), nullable=False),
    sa.Column('delta', sa.Float(), nullable=False),
    sa.Column('drivers_json', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scenario_results_id'), 'scenario_results', ['id'], unique=False)
    op.create_table('threat_scenarios',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('threat_actor', sa.String(length=100), nullable=True),
    sa.Column('attack_vector', sa.String(length=100), nullable=True),
    sa.Column('likelihood_score', sa.Float(), nullable=True),
    sa.Column('financial_impact', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['business_services.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_scenarios_id'), 'threat_scenarios', ['id'], unique=False)
    op.create_table('asset_controls',
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('control_id', sa.String(length=36), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('effectiveness_pct', sa.Float(), nullable=True),
    sa.Column('last_checked', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['control_id'], ['security_controls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_controls_id'), 'asset_controls', ['id'], unique=False)
    op.create_table('incidents',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('asset_id', sa.String(length=36), nullable=True),
    sa.Column('incident_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('incident_type', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('estimated_financial_loss', sa.Float(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['service_id'], ['business_services.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_incidents_id'), 'incidents', ['id'], unique=False)
    op.create_index(op.f('ix_incidents_incident_number'), 'incidents', ['incident_number'], unique=True)
    op.create_table('vulnerabilities',
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('cve_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=50), nullable=True),
    sa.Column('cvss_score', sa.Float(), nullable=True),
    sa.Column('exploitability_score', sa.Float(), nullable=True),
    sa.Column('exposure_modifier', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('risk_contribution', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_cve_id'), 'vulnerabilities', ['cve_id'], unique=False)
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_cve_id'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_incidents_incident_number'), table_name='incidents')
    op.drop_index(op.f('ix_incidents_id'), table_name='incidents')
    op.drop_table('incidents')
    op.drop_index(op.f('ix_asset_controls_id'), table_name='asset_controls')
    op.drop_table('asset_controls')
    op.drop_index(op.f('ix_threat_scenarios_id'), table_name='threat_scenarios')
    op.drop_table('threat_scenarios')
    op.drop_index(op.f('ix_scenario_results_id'), table_name='scenario_results')
    op.drop_table('scenario_results')
    op.drop_index(op.f('ix_risk_drivers_id'), table_name='risk_drivers')
    op.drop_table('risk_drivers')
    op.drop_index(op.f('ix_evidence_records_id'), table_name='evidence_records')
    op.drop_table('evidence_records')
    op.drop_index(op.f('ix_decision_approvals_id'), table_name='decision_approvals')
    op.drop_table('decision_approvals')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_id_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_security_controls_id'), table_name='security_controls')
    op.drop_index(op.f('ix_security_controls_code'), table_name='security_controls')
    op.drop_table('security_controls')
    op.drop_index(op.f('ix_scenarios_id'), table_name='scenarios')
    op.drop_table('scenarios')
    op.drop_index(op.f('ix_risk_snapshots_snapshot_date'), table_name='risk_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_id'), table_name='risk_snapshots')
    op.drop_index(op.f('ix_risk_snapshots_entity_id'), table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index(op.f('ix_optimization_runs_id'), table_name='optimization_runs')
    op.drop_table('optimization_runs')
    op.drop_index(op.f('ix_model_versions_id'), table_name='model_versions')
    op.drop_table('model_versions')
    op.drop_index(op.f('ix_investment_initiatives_id'), table_name='investment_initiatives')
    op.drop_index(op.f('ix_investment_initiatives_code'), table_name='investment_initiatives')
    op.drop_table('investment_initiatives')
    op.drop_index(op.f('ix_evidence_sources_id'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_index(op.f('ix_business_services_id'), table_name='business_services')
    op.drop_table('business_services')
    op.drop_index(op.f('ix_audit_events_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
